version: "3"
services:
  description:
    image: mysql/mysql-server:5.7.21-1.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=root4chompy
      - MYSQL_ROOT_HOST=172.*.*.*
      - MYSQL_DATABASE=chompy_business
      - MYSQL_USER=chompy
      - MYSQL_PASSWORD=chompydatabase
      - MYSQL_LOG_CONSOLE=true
    container_name: businessDb
    restart: always
    ports:
      - "33060:3306"